export const lang = {
  english: {
    searchButton: "GPT Search",
    SignOutButton: "Sign Out",
    playButton: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing Movies",
    topRated: "Top Rated Movies",
    popular: "Popular Movies",
    seeAll: "See All",
    gptSearchTitle: "What do you want to watch?",
    gptSearchDescription: "Search movies with the power of AI — describe a mood, plot, or vibe.",
    gptSearchPlaceholder: "e.g. A mind-bending sci-fi thriller like Inception...",
    search: "Search",
  },

  hindi: {
    searchButton: "GPT सर्च",
    SignOutButton: "साइन आउट",
    playButton: "चलाएँ",
    moreInfo: "अधिक जानकारी",
    nowPlaying: "अभी चल रही फ़िल्में",
    topRated: "सर्वाधिक रेटिंग वाली फ़िल्में",
    popular: "लोकप्रिय फ़िल्में",
    seeAll: "सभी देखें",
    gptSearchTitle: "आप क्या देखना चाहते हैं?",
    gptSearchDescription: "AI की मदद से फ़िल्में खोजें — अपना मूड, कहानी या पसंद बताएं。",
    gptSearchPlaceholder: "जैसे: Inception जैसी दिमाग घुमा देने वाली साइंस-फिक्शन थ्रिलर...",
    search: "सर्च",
  },

  spanish: {
    searchButton: "Búsqueda GPT",
    SignOutButton: "Cerrar sesión",
    playButton: "Reproducir",
    moreInfo: "Más información",
    nowPlaying: "Películas en cartelera",
    topRated: "Películas mejor valoradas",
    popular: "Películas populares",
    seeAll: "Ver todo",
    gptSearchTitle: "¿Qué quieres ver?",
    gptSearchDescription: "Busca películas con el poder de la IA: describe un estado de ánimo, trama o ambiente.",
    gptSearchPlaceholder: "ej. Un thriller de ciencia ficción alucinante como Inception...",
    search: "Buscar",
  },

  french: {
    searchButton: "Recherche GPT",
    SignOutButton: "Déconnexion",
    playButton: "Lecture",
    moreInfo: "Plus d'infos",
    nowPlaying: "Films à l'affiche",
    topRated: "Films les mieux notés",
    popular: "Films populaires",
    seeAll: "Voir tout",
    gptSearchTitle: "Que voulez-vous regarder ?",
    gptSearchDescription: "Recherchez des films grâce à l'IA — décrivez une ambiance, une intrigue ou un style.",
    gptSearchPlaceholder: "ex. Un thriller de science-fiction captivant comme Inception...",
    search: "Rechercher",
  },

  german: {
    searchButton: "GPT-Suche",
    SignOutButton: "Abmelden",
    playButton: "Abspielen",
    moreInfo: "Weitere Infos",
    nowPlaying: "Aktuelle Filme",
    topRated: "Bestbewertete Filme",
    popular: "Beliebte Filme",
    seeAll: "Alle ansehen",
    gptSearchTitle: "Was möchtest du sehen?",
    gptSearchDescription: "Suche Filme mit der Kraft der KI — beschreibe eine Stimmung, Handlung oder Atmosphäre.",
    gptSearchPlaceholder: "z.B. Ein verwirrender Sci-Fi-Thriller wie Inception...",
    search: "Suchen",
  },

  italian: {
    searchButton: "Ricerca GPT",
    SignOutButton: "Esci",
    playButton: "Riproduci",
    moreInfo: "Più info",
    nowPlaying: "Film in sala",
    topRated: "Film più votati",
    popular: "Film popolari",
    seeAll: "Vedi tutti",
    gptSearchTitle: "Cosa vuoi guardare?",
    gptSearchDescription: "Cerca film con la potenza dell'IA: descrivi un'atmosfera, una trama o uno stile.",
    gptSearchPlaceholder: "es. Un thriller fantascientifico sconvolgente come Inception...",
    search: "Cerca",
  },

  portuguese: {
    searchButton: "Pesquisa GPT",
    SignOutButton: "Sair",
    playButton: "Reproduzir",
    moreInfo: "Mais Informações",
    nowPlaying: "Filmes em Cartaz",
    topRated: "Filmes Mais Bem Avaliados",
    popular: "Filmes Populares",
    seeAll: "Ver Tudo",
    gptSearchTitle: "O que você quer assistir?",
    gptSearchDescription: "Pesquise filmes com o poder da IA — descreva um clima, enredo ou vibração.",
    gptSearchPlaceholder: "ex. Um thriller de ficção científica alucinante como Inception...",
    search: "Pesquisar",
  },

  russian: {
    searchButton: "GPT Поиск",
    SignOutButton: "Выйти",
    playButton: "Смотреть",
    moreInfo: "Подробнее",
    nowPlaying: "Сейчас в кино",
    topRated: "Лучшие фильмы",
    popular: "Популярные фильмы",
    seeAll: "Смотреть все",
    gptSearchTitle: "Что вы хотите посмотреть?",
    gptSearchDescription: "Ищите фильмы с помощью ИИ — опишите настроение, сюжет или атмосферу.",
    gptSearchPlaceholder: "напр. Захватывающий научно-фантастический триллер вроде Начала...",
    search: "Поиск",
  },

  chinese: {
    searchButton: "GPT 搜索",
    SignOutButton: "登出",
    playButton: "播放",
    moreInfo: "更多信息",
    nowPlaying: "正在热映",
    topRated: "最高评分电影",
    popular: "热门电影",
    seeAll: "查看全部",
    gptSearchTitle: "你想看什么？",
    gptSearchDescription: "用AI的力量搜索电影——描述一种心情、情节或氛围。",
    gptSearchPlaceholder: "例如：一部像《盗梦空间》一样烧脑的科幻惊悚片...",
    search: "搜索",
  },

  japanese: {
    searchButton: "GPT 検索",
    SignOutButton: "サインアウト",
    playButton: "再生",
    moreInfo: "詳細情報",
    nowPlaying: "上映中の映画",
    topRated: "高評価の映画",
    popular: "人気の映画",
    seeAll: "すべて見る",
    gptSearchTitle: "何を見たいですか？",
    gptSearchDescription: "AIの力で映画を検索 — 気分、あらすじ、雰囲気を説明してください。",
    gptSearchPlaceholder: "例: 『インセプション』のような難解なSFスリラー...",
    search: "検索",
  },

  korean: {
    searchButton: "GPT 검색",
    SignOutButton: "로그아웃",
    playButton: "재생",
    moreInfo: "상세 정보",
    nowPlaying: "현재 상영 중인 영화",
    topRated: "최고 평점 영화",
    popular: "인기 영화",
    seeAll: "모두 보기",
    gptSearchTitle: "무엇을 보고 싶으신가요?",
    gptSearchDescription: "AI의 힘으로 영화를 검색하세요 - 기분, 줄거리 또는 분위기를 설명하세요.",
    gptSearchPlaceholder: "예: 인셉션 같은 기막힌 SF 스릴러...",
    search: "검색",
  },

  arabic: {
    searchButton: "بحث GPT",
    SignOutButton: "تسجيل الخروج",
    playButton: "تشغيل",
    moreInfo: "مزيد من المعلومات",
    nowPlaying: "يُعرض الآن",
    topRated: "الأعلى تقييماً",
    popular: "أفلام شهيرة",
    seeAll: "عرض الكل",
    gptSearchTitle: "ماذا تريد أن تشاهد؟",
    gptSearchDescription: "ابحث عن الأفلام بقوة الذكاء الاصطناعي — صف حالتك المزاجية أو القصة أو الأجواء.",
    gptSearchPlaceholder: "مثال: فيلم خيال علمي مثير ومذهل مثل Inception...",
    search: "بحث",
  },

  bengali: {
    searchButton: "GPT অনুসন্ধান",
    SignOutButton: "সাইন আউট",
    playButton: "চালান",
    moreInfo: "আরও তথ্য",
    nowPlaying: "এখন চলছে",
    topRated: "শীর্ষ রেট করা সিনেমা",
    popular: "জনপ্রিয় সিনেমা",
    seeAll: "সব দেখুন",
    gptSearchTitle: "আপনি কী দেখতে চান?",
    gptSearchDescription: "AI এর শক্তি দিয়ে সিনেমা খুঁজুন — একটি মেজাজ, প্লট বা ভাইব বর্ণনা করুন।",
    gptSearchPlaceholder: "যেমন: ইনসেপশনের মতো মন ঘুরিয়ে দেওয়া সাই-ফাই থ্রিলার...",
    search: "অনুসন্ধান",
  },

  marathi: {
    searchButton: "GPT शोध",
    SignOutButton: "साइन आउट",
    playButton: "प्ले करा",
    moreInfo: "अधिक माहिती",
    nowPlaying: "सध्या सुरू असलेले चित्रपट",
    topRated: "सर्वाधिक रेटिंग असलेले चित्रपट",
    popular: "लोकप्रिय चित्रपट",
    seeAll: "सर्व पहा",
    gptSearchTitle: "तुम्हाला काय बघायला आवडेल?",
    gptSearchDescription: "AI च्या मदतीने चित्रपट शोधा — तुमचा मूड, कथा किंवा वातावरण सांगा.",
    gptSearchPlaceholder: "उदा. Inception सारखा डोके चक्रावून टाकणारा साय-फाय थ्रिलर...",
    search: "शोध",
  },

  telugu: {
    searchButton: "GPT సెర్చ్",
    SignOutButton: "సైన్ అవుట్",
    playButton: "ప్లే",
    moreInfo: "మరింత సమాచారం",
    nowPlaying: "ఇప్పుడు ఆడుతున్న సినిమాలు",
    topRated: "అత్యుత్తమ రేటింగ్ ఉన్న సినిమాలు",
    popular: "ప్రసిద్ధ సినిమాలు",
    seeAll: "అన్నీ చూడండి",
    gptSearchTitle: "మీరు ఏమి చూడాలనుకుంటున్నారు?",
    gptSearchDescription: "AI సహాయంతో సినిమాలను వెతకండి — మూడ్, కథ లేదా వైబ్‌ని వివరించండి.",
    gptSearchPlaceholder: "ఉదా. ఇన్సెప్షన్ లాంటి మైండ్ బ్లోయింగ్ సైన్స్ ఫిక్షన్ థ్రిల్లర్...",
    search: "సెర్చ్",
  },

  tamil: {
    searchButton: "GPT தேடல்",
    SignOutButton: "வெளியேறு",
    playButton: "இயக்கு",
    moreInfo: "மேலும் தகவல்",
    nowPlaying: "தற்போது ஓடும் திரைப்படங்கள்",
    topRated: "அதிக ரேட்டிங் பெற்ற படங்கள்",
    popular: "பிரபலமான படங்கள்",
    seeAll: "அனைத்தையும் காண்க",
    gptSearchTitle: "நீங்கள் என்ன பார்க்க விரும்புகிறீர்கள்?",
    gptSearchDescription: "AI மூலம் திரைப்படங்களைத் தேடுங்கள் - உங்கள் மனநிலை, கதை அல்லது சூழலை விவரிக்கவும்.",
    gptSearchPlaceholder: "உ.ம். இன்செப்ஷன் போன்ற சிந்தனையைத் தூண்டும் சயின்ஸ் பிக்ஷன் த்ரில்லர்...",
    search: "தேடல்",
  },

  gujarati: {
    searchButton: "GPT સર્ચ",
    SignOutButton: "સાઇન આઉટ",
    playButton: "ચલાવો",
    moreInfo: "વધુ માહિતી",
    nowPlaying: "હાલમાં ચાલી રહેલી ફિલ્મો",
    topRated: "ટોચના રેટિંગ વાળી ફિલ્મો",
    popular: "લોકપ્રિય ફિલ્મો",
    seeAll: "બધું જુઓ",
    gptSearchTitle: "તમે શું જોવા માંગો છો?",
    gptSearchDescription: "AI ની મદદથી ફિલ્મો શોધો — તમારો મૂડ, વાર્તા અથવા વાતાવરણ જણાવો.",
    gptSearchPlaceholder: "દા.ત. ઇન્સેપ્શન જેવી માઇન્ડ-બેન્ડિંગ સાઇ-ફાઇ થ્રિલર...",
    search: "સર્ચ",
  },

  punjabi: {
    searchButton: "GPT ਖੋਜ",
    SignOutButton: "ਸਾਈਨ ਆਊਟ",
    playButton: "ਚਲਾਓ",
    moreInfo: "ਹੋਰ ਜਾਣਕਾਰੀ",
    nowPlaying: "ਹੁਣ ਚੱਲ ਰਹੀਆਂ ਫਿਲਮਾਂ",
    topRated: "ਸਿਖਰਲੀ ਰੇਟਿੰਗ ਵਾਲੀਆਂ ਫਿਲਮਾਂ",
    popular: "ਮਸ਼ਹੂਰ ਫਿਲਮਾਂ",
    seeAll: "ਸਭ ਦੇਖੋ",
    gptSearchTitle: "ਤੁਸੀਂ ਕੀ ਦੇਖਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    gptSearchDescription: "AI ਦੀ ਮਦਦ ਨਾਲ ਫਿਲਮਾਂ ਲੱਭੋ — ਆਪਣਾ ਮੂਡ, ਕਹਾਣੀ ਜਾਂ ਮਾਹੌਲ ਦੱਸੋ।",
    gptSearchPlaceholder: "ਜਿਵੇਂ ਕਿ: ਇਨਸੈਪਸ਼ਨ ਵਰਗੀ ਦਿਮਾਗ ਘੁੰਮਾਉਣ ਵਾਲੀ ਸਾਇੰਸ-ਫਿਕਸ਼ਨ ਥ੍ਰਿਲਰ...",
    search: "ਖੋਜ",
  },

  urdu: {
    searchButton: "GPT تلاش",
    SignOutButton: "سائن آؤٹ",
    playButton: "چلائیں",
    moreInfo: "مزید معلومات",
    nowPlaying: "اب چل رہی فلمیں",
    topRated: "بہترین درجہ بندی والی فلمیں",
    popular: "مقبول فلمیں",
    seeAll: "سب دیکھیں",
    gptSearchTitle: "آپ کیا دیکھنا چاہتے ہیں?",
    gptSearchDescription: "AI کی مدد سے فلمیں تلاش کریں — اپنا موڈ، کہانی یا ماحول بتائیں۔",
    gptSearchPlaceholder: "جیسے: Inception جیسی دماغ گھما دینے والی سائنس فکشن تھرلر...",
    search: "تلاش",
  }
};